version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: clinicafacil-db
    environment:
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinicalocal
      POSTGRES_DB: clinicafacil
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U clinica -d clinicafacil']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: clinicafacil-redis
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: clinicafacil-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: unless-stopped

volumes:
  pgdata:
  redisdata: